package com.orca.compiler.core.symbols;

import java.util.EnumSet;

/**
 * Represents the attributes of a binding in the compiler.
 */
public enum BindingAttribute {
    /**
     * Static binding, which means the binding is associated with the namespace
     * or type itself rather than an instance of the type. For example, a static
     * method would have this attribute.
     */
    STATIC("static"),
    /**
     * Source binding, which means the binding is defined in the source code.
     */
    SOURCE(""),
    /**
     * Instance binding, which means the binding is associated with an instance
     * of a type. For example, an instance method and a field would have this
     * attribute.
     */
    INSTANCE(""),
    /**
     * Instance-only binding, which means the binding can only be accessed
     * through an instance of a type and cannot be accessed statically.
     */
    INSTANCE_ONLY("instance-only"),
    /**
     * Intrinsic binding, which means the binding is provided by the language or
     * runtime environment.
     */
    INTRINSIC("intrinsic"),
    /**
     * Synthesized binding, which means the binding is generated by the
     * compiler.
     *
     * @implNote By default, symbols are considered user-defined unless they are
     * explicitly marked as synthesized.
     */
    SYNTHESIZED("synthesized"),
    /**
     * Entry point binding, which means the binding is the entry point of the
     * program, such as the `main` method.
     */
    ENTRY_POINT("entry-point"),
    /**
     * JVM external binding, which means the binding is defined in the JVM and
     * is not part of the source code.
     */
    JVM_EXTERNAL("jvm-external"),
    /**
     * Mutable binding, which means the binding is mutable and can be modified
     */
    MUTABLE("mutable"),
    /**
     * Immutable binding, which means the binding is immutable and cannot be
     * modified
     */
    IMMUTABLE("immutable"),
    /**
     * Constant binding, which means the binding is a compile-time constant.
     */
    CONSTANT("constant");

    private final String displayName;

    BindingAttribute(String displayName) {
        this.displayName = displayName;
    }

    public String getDisplayName() {
        return displayName;
    }

    public static EnumSet<BindingAttribute> getAttributesFromModifiers(int modifiers) {
        var attributes = EnumSet.noneOf(BindingAttribute.class);
        if (SymbolModifiers.isStatic(modifiers)) {
            attributes.add(STATIC);
        }
        if (SymbolModifiers.isInstance(modifiers)) {
            attributes.add(INSTANCE);
        }
        if (SymbolModifiers.isIntrinsic(modifiers)) {
            attributes.add(INTRINSIC);
        }
        if (SymbolModifiers.isSynthesized(modifiers)) {
            attributes.add(SYNTHESIZED);
        }
        if (SymbolModifiers.isInstanceOnly(modifiers)) {
            attributes.add(INSTANCE_ONLY);
        }
        if (SymbolModifiers.isSource(modifiers)) {
            attributes.add(SOURCE);
        }
        if (SymbolModifiers.isJvmExternal(modifiers)) {
            attributes.add(JVM_EXTERNAL);
        }
        if (SymbolModifiers.isEntryPoint(modifiers)) {
            attributes.add(ENTRY_POINT);
        }
        if (SymbolModifiers.isConstant(modifiers)) {
            attributes.add(CONSTANT);
        }
        if (SymbolModifiers.isImmutable(modifiers)) {
            attributes.add(IMMUTABLE);
        } else {
            attributes.add(MUTABLE);
        }

        return attributes;
    }
}
